language: generic

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=3.4 }
     - { os: linux, env: PYTHON_VERSION=3.5 }
     - { os: osx, env: PYTHON_VERSION=3.5 }

sudo: false

before_install:
    - source devtools/travis-ci/setup_env.sh

install:
    - python setup.py install

script:
    - nosetests -vs .

after_success:
    - echo "after_success"
    # - coveralls

notifications:
  email: false
